<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="3" failed="0" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-10-16T18:12:55 IST" name="Default suite" finished-at="2023-10-16T18:13:06 IST" duration-ms="11481">
    <groups>
    </groups>
    <test started-at="2023-10-16T18:12:55 IST" name="Default test" finished-at="2023-10-16T18:13:06 IST" duration-ms="11481">
      <class name="org.test.Testing">
        <test-method is-config="true" signature="beforeClass()[pri:0, instance:org.test.Testing@38425407]" started-at="2023-10-16T18:12:55 IST" name="beforeClass" finished-at="2023-10-16T18:12:57 IST" duration-ms="2565" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:org.test.Testing@38425407]" started-at="2023-10-16T18:12:57 IST" name="beforeMethod" finished-at="2023-10-16T18:12:58 IST" duration-ms="1035" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="createNewAccount()[pri:0, instance:org.test.Testing@38425407]" started-at="2023-10-16T18:12:58 IST" name="createNewAccount" finished-at="2023-10-16T18:13:00 IST" duration-ms="1859" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createNewAccount -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:org.test.Testing@38425407]" started-at="2023-10-16T18:13:00 IST" name="afterMethod" finished-at="2023-10-16T18:13:00 IST" duration-ms="191" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:org.test.Testing@38425407]" started-at="2023-10-16T18:13:00 IST" name="beforeMethod" finished-at="2023-10-16T18:13:01 IST" duration-ms="532" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="forgotPassword()[pri:0, instance:org.test.Testing@38425407]" started-at="2023-10-16T18:13:01 IST" name="forgotPassword" finished-at="2023-10-16T18:13:02 IST" duration-ms="869" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- forgotPassword -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:org.test.Testing@38425407]" started-at="2023-10-16T18:13:02 IST" name="afterMethod" finished-at="2023-10-16T18:13:02 IST" duration-ms="155" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:org.test.Testing@38425407]" started-at="2023-10-16T18:13:02 IST" name="beforeMethod" finished-at="2023-10-16T18:13:03 IST" duration-ms="506" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="function()[pri:0, instance:org.test.Testing@38425407]" started-at="2023-10-16T18:13:03 IST" name="function" finished-at="2023-10-16T18:13:03 IST" duration-ms="254" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- function -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:org.test.Testing@38425407]" started-at="2023-10-16T18:13:03 IST" name="afterMethod" finished-at="2023-10-16T18:13:06 IST" duration-ms="2804" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="afterClass()[pri:0, instance:org.test.Testing@38425407]" started-at="2023-10-16T18:13:06 IST" name="afterClass" finished-at="2023-10-16T18:13:06 IST" duration-ms="659" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [true] but found [false],
expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [false],
expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at org.test.Testing.afterClass(Testing.java:26)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:361)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:296)
at org.testng.internal.invokers.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:222)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:131)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- org.test.Testing -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
